### PR TITLE
Migrated to .net core 3.0 & .net standard 2.1

### PR DESCRIPTION
**Pull request by lablabla**

### CODE REVIEW

**Comment by ziyasal** [comment]
Hi @lablabla thank tou foe your contribution 😊

**Comment by lablabla** [comment]
Hi @ziyasal 
Glad to help

For some reason it included a lot of commits I didn't mean to include. I only wanted to PR the first one that updates to standard

I suggest you remove all my testing and experimenting with appveyor

**Comment by ziyasal** [comment]
@lablabla that's fine, could you please create pr that removes them?

**Comment by lablabla** [comment]
Done. Sorry if it's a bit messy. Kinda new to the all contributing and PR thing

**Pull request merged**
